/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package it.tsp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author utentepc
 */
public class WinViaggi extends javax.swing.JFrame {

    static final String DB_URL = "jdbc:mysql://localhost:3306/pinastravel";
    static final String USER = "root";
    static final String PASS = "root";
    Connection conn;
    ArrayList<Integer> listIdaccounturist = new ArrayList<Integer>();
    ArrayList<Integer> listIdtravel = new ArrayList<Integer>();
    ArrayList<Integer> listIdpartecipants = new ArrayList<Integer>();

    /**
     * Creates new form WinViaggi
     */
    public WinViaggi() {
        initComponents();
        refreshListaccounturist();
        refreshListtravel();
        refreshtbPartecipants();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPinasTravel = new javax.swing.JLabel();
        lbNewAccounTurist = new javax.swing.JLabel();
        lbfname = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lbphone = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        txFname = new javax.swing.JTextField();
        txLname = new javax.swing.JTextField();
        txPhone = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        btSigninTurist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAccounTurist = new javax.swing.JList<>();
        lbAccounTurist = new javax.swing.JLabel();
        lbNewTravel = new javax.swing.JLabel();
        lbDestination = new javax.swing.JLabel();
        lbLength = new javax.swing.JLabel();
        lbDayPrice = new javax.swing.JLabel();
        lbCarriage = new javax.swing.JLabel();
        lbDepartureDate = new javax.swing.JLabel();
        txLength = new javax.swing.JTextField();
        txDestination = new javax.swing.JTextField();
        txDepartureDate = new javax.swing.JTextField();
        txCarriage = new javax.swing.JTextField();
        btSigninTravel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTravel = new javax.swing.JList<>();
        lbTravel = new javax.swing.JLabel();
        spDayPrice = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPartecipants = new javax.swing.JTable();
        lbPartecipants = new javax.swing.JLabel();
        lbPrezzoPrenotazione = new javax.swing.JLabel();
        lbDestinationP = new javax.swing.JLabel();
        txDestinationP = new javax.swing.JTextField();
        lbFnameP = new javax.swing.JLabel();
        lbLnameP = new javax.swing.JLabel();
        txFnameP = new javax.swing.JTextField();
        btPartecipants = new javax.swing.JButton();
        txLnameP = new javax.swing.JTextField();
        btDeleteTurist = new javax.swing.JButton();
        btDeleteTravel = new javax.swing.JButton();
        btDeletePartecipants = new javax.swing.JButton();
        labelD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        lbPinasTravel.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lbPinasTravel.setText("Welcome to Pina's Travels");

        lbNewAccounTurist.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbNewAccounTurist.setText("Nuovo clt");

        lbfname.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbfname.setText("Nome:");

        lblname.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblname.setText("Cognome:");

        lbphone.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbphone.setText("Telefono:");

        lbemail.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbemail.setText("email:");

        txFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFnameActionPerformed(evt);
            }
        });
        txFname.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txFnamePropertyChange(evt);
            }
        });

        txLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txLnameActionPerformed(evt);
            }
        });
        txLname.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txLnamePropertyChange(evt);
            }
        });

        txPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPhoneActionPerformed(evt);
            }
        });
        txPhone.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txPhonePropertyChange(evt);
            }
        });

        txEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEmailActionPerformed(evt);
            }
        });
        txEmail.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txEmailPropertyChange(evt);
            }
        });

        btSigninTurist.setText("Registra");
        btSigninTurist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSigninTuristActionPerformed(evt);
            }
        });

        lstAccounTurist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstAccounTurist);

        lbAccounTurist.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbAccounTurist.setText("Lista clt");

        lbNewTravel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbNewTravel.setText("Nuova Destinazione");

        lbDestination.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbDestination.setText("Città:");

        lbLength.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbLength.setText("Durata (gg):");

        lbDayPrice.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbDayPrice.setText("prezzo/gg:");

        lbCarriage.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbCarriage.setText("Trasporto:");

        lbDepartureDate.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbDepartureDate.setText("Data partenza:");

        txLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txLengthActionPerformed(evt);
            }
        });
        txLength.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txLengthPropertyChange(evt);
            }
        });

        txDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDestinationActionPerformed(evt);
            }
        });
        txDestination.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txDestinationPropertyChange(evt);
            }
        });

        txDepartureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDepartureDateActionPerformed(evt);
            }
        });
        txDepartureDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txDepartureDatePropertyChange(evt);
            }
        });

        txCarriage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCarriageActionPerformed(evt);
            }
        });
        txCarriage.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txCarriagePropertyChange(evt);
            }
        });

        btSigninTravel.setText("Registra");
        btSigninTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSigninTravelActionPerformed(evt);
            }
        });

        lstTravel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstTravel);

        lbTravel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbTravel.setText("Lista viaggi");

        tbPartecipants.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tbPartecipants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cognome", "Città", "PrezzoFinale"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbPartecipants);
        if (tbPartecipants.getColumnModel().getColumnCount() > 0) {
            tbPartecipants.getColumnModel().getColumn(0).setResizable(false);
            tbPartecipants.getColumnModel().getColumn(1).setResizable(false);
            tbPartecipants.getColumnModel().getColumn(2).setResizable(false);
            tbPartecipants.getColumnModel().getColumn(3).setResizable(false);
        }

        lbPartecipants.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbPartecipants.setText("Lista Prenotazioni");

        lbPrezzoPrenotazione.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbPrezzoPrenotazione.setText("Prenotazione Viaggi");

        lbDestinationP.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbDestinationP.setText("Città:");

        txDestinationP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDestinationPActionPerformed(evt);
            }
        });
        txDestinationP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txDestinationPPropertyChange(evt);
            }
        });

        lbFnameP.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbFnameP.setText("Nome:");

        lbLnameP.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lbLnameP.setText("Cognome:");

        txFnameP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFnamePActionPerformed(evt);
            }
        });
        txFnameP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txFnamePPropertyChange(evt);
            }
        });

        btPartecipants.setText("Prenota");
        btPartecipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPartecipantsActionPerformed(evt);
            }
        });

        txLnameP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txLnamePActionPerformed(evt);
            }
        });
        txLnameP.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txLnamePPropertyChange(evt);
            }
        });

        btDeleteTurist.setText("Cancella");

        btDeleteTravel.setText("Cancella");

        btDeletePartecipants.setText("Cancella");

        labelD.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        labelD.setText("Per cancellare un account seleziona dalla lista e clicca su:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbfname)
                                    .addComponent(lblname)
                                    .addComponent(lbphone)
                                    .addComponent(lbemail)
                                    .addComponent(btSigninTurist))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txFname, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(529, 529, 529))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPinasTravel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAccounTurist)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPrezzoPrenotazione)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbFnameP)
                                            .addComponent(lbDestinationP)
                                            .addComponent(lbLnameP)
                                            .addComponent(btPartecipants))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txDestinationP, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                            .addComponent(txLnameP)
                                            .addComponent(txFnameP, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btDeletePartecipants))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbPartecipants)
                                        .addGap(268, 268, 268))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbDestination)
                                    .addComponent(lbLength)
                                    .addComponent(lbDayPrice)
                                    .addComponent(lbCarriage))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txCarriage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spDayPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txLength, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(labelD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btDeleteTurist)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane1))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNewTravel)
                            .addComponent(lbNewAccounTurist, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 614, Short.MAX_VALUE)
                        .addComponent(lbTravel)
                        .addGap(319, 319, 319))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btSigninTravel)
                            .addComponent(lbDepartureDate))
                        .addGap(18, 18, 18)
                        .addComponent(btDeleteTravel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPinasTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNewAccounTurist)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbfname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbphone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbemail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAccounTurist)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSigninTurist)
                            .addComponent(btDeleteTurist)
                            .addComponent(labelD))
                        .addGap(51, 51, 51)
                        .addComponent(lbNewTravel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLength)
                            .addComponent(txLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDayPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spDayPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCarriage, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txCarriage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDepartureDate)
                            .addComponent(txDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTravel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSigninTravel)
                    .addComponent(btDeleteTravel))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPartecipants)
                    .addComponent(lbPrezzoPrenotazione, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFnameP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFnameP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txLnameP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLnameP, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txDestinationP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDestinationP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btPartecipants)
                            .addComponent(btDeletePartecipants)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFnameActionPerformed

    private void txFnamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txFnamePropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_txFnamePropertyChange

    private void txLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txLnameActionPerformed

    private void txLnamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txLnamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txLnamePropertyChange

    private void txPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPhoneActionPerformed

    private void txPhonePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txPhonePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txPhonePropertyChange

    private void txEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txEmailActionPerformed

    private void txEmailPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txEmailPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txEmailPropertyChange

    private void btSigninTuristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSigninTuristActionPerformed
        // TODO add your handling code here:
        String nome = txFname.getText();
        String cognome = txLname.getText();
        String telefono = txPhone.getText();
        String email = txEmail.getText();

        AccounTurist turist = new AccounTurist(nome, cognome, telefono, email);
        txFname.setText("");
        txLname.setText("");
        txPhone.setText("");
        txEmail.setText("");

        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement("insert INTO accounturist(`Fname`, `Lname`, `Phone`, `Email`)"
                    + "values(?,?,?,?)");
            stmt.setString(1, nome);
            stmt.setString(2, cognome);
            stmt.setString(3, telefono);
            stmt.setString(4, email);
            int rows = stmt.executeUpdate();
            System.out.println("Row impacted: " + rows);
            refreshListaccounturist();

        } catch (Exception e) {
            System.out.println(e);

        }

    }//GEN-LAST:event_btSigninTuristActionPerformed

    private void btDeleteTuristActionPerformed(java.awt.event.ActionEvent evt) {
    int selectedRow = lstAccounTurist.getSelectedIndex();
    if (selectedRow == -1) {
        System.out.println("Seleziona un turista dalla lista");
        return;
    }

    String nome = (String) lstAccounTurist.getModel().getElementAt(selectedRow);
    String cognome = (String) lstAccounTurist.getModel().getElementAt(selectedRow);
    try {
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        PreparedStatement stmt = conn.prepareStatement("DELETE FROM accounturist WHERE Fname = ? AND Lname = ?");
        stmt.setString(1, nome);
        stmt.setString(2, cognome);
        int rows = stmt.executeUpdate();
        System.out.println("Row deleted: " + rows);

        refreshListaccounturist();
        txEmail.setText("");
    } catch (SQLException e) {
        System.out.println(e);
    }
}


    private void txLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txLengthActionPerformed

    private void txLengthPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txLengthPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txLengthPropertyChange

    private void txDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDestinationActionPerformed

    private void txDestinationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txDestinationPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txDestinationPropertyChange

    private void txDepartureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDepartureDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDepartureDateActionPerformed

    private void txDepartureDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txDepartureDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txDepartureDatePropertyChange

    private void txCarriageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCarriageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCarriageActionPerformed

    private void txCarriagePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txCarriagePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txCarriagePropertyChange

    private void btSigninTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSigninTravelActionPerformed
        // TODO add your handling code here:
        String città = txDestination.getText();
        String durata = txLength.getText();
        Number numero = (Number) spDayPrice.getValue();
        BigDecimal prezzo = BigDecimal.valueOf(numero.doubleValue());
        String trasporto = txCarriage.getText();

        String dateString = txDepartureDate.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        LocalDateTime datapartenza = LocalDateTime.parse(dateString, formatter);

        Travel trip = new Travel(città, durata, prezzo, trasporto, datapartenza);
        txDestination.setText("");
        txLength.setText("");
        spDayPrice.setValue(numero);
        txCarriage.setText("");
        txDepartureDate.setText("");

        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement("insert INTO travel (Destination, Length, DayPrice, Carriage, DepartureDate) "
                    + "values(?,?,?,?,?)");
            stmt.setString(1, città);
            stmt.setString(2, durata);
            stmt.setString(3, prezzo.toString());
            stmt.setString(4, trasporto);
            String datapartenzaString = datapartenza.toString();
            stmt.setString(5, datapartenzaString);
            int rows = stmt.executeUpdate();
            System.out.println("Row impacted: " + rows);
            refreshListtravel();

        } catch (Exception e) {
            System.out.println(e);

        }


    }//GEN-LAST:event_btSigninTravelActionPerformed

    private void txDestinationPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDestinationPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDestinationPActionPerformed

    private void txDestinationPPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txDestinationPPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txDestinationPPropertyChange

    private void txFnamePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFnamePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFnamePActionPerformed

    private void txFnamePPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txFnamePPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txFnamePPropertyChange

    private void btPartecipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPartecipantsActionPerformed
        // TODO add your handling code here:
        String nome = txFnameP.getText();
        String cognome = txLnameP.getText();
        String città = txDestinationP.getText();
        String prezzoFinale = "0";

        Partecipants partecip = new Partecipants(nome, cognome, città);
        txFnameP.setText("");
        txLnameP.setText("");
        txDestinationP.setText("");

        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement("UPDATE partecipants p INNER JOIN travel t ON p.Destination = t.Destination SET p.TotalPrice = (t.DayPrice * t.Length)");
            stmt.executeUpdate();

            PreparedStatement insertStmt = conn.prepareStatement("INSERT INTO partecipants (Fname, Lname, Destination, TotalPrice) "
                    + "VALUES (?, ?, ?, ?)");
            insertStmt.setString(1, nome);
            insertStmt.setString(2, cognome);
            insertStmt.setString(3, città);
            insertStmt.setString(4, prezzoFinale);
            int rows = insertStmt.executeUpdate();

            System.out.println("Row impacted: " + rows);
            refreshtbPartecipants();

        } catch (Exception e) {
            System.out.println(e);

        }


    }//GEN-LAST:event_btPartecipantsActionPerformed

    private void txLnamePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txLnamePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txLnamePActionPerformed

    private void txLnamePPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txLnamePPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txLnamePPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinViaggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinViaggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinViaggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinViaggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinViaggi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeletePartecipants;
    private javax.swing.JButton btDeleteTravel;
    private javax.swing.JButton btDeleteTurist;
    private javax.swing.JButton btPartecipants;
    private javax.swing.JButton btSigninTravel;
    private javax.swing.JButton btSigninTurist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelD;
    private javax.swing.JLabel lbAccounTurist;
    private javax.swing.JLabel lbCarriage;
    private javax.swing.JLabel lbDayPrice;
    private javax.swing.JLabel lbDepartureDate;
    private javax.swing.JLabel lbDestination;
    private javax.swing.JLabel lbDestinationP;
    private javax.swing.JLabel lbFnameP;
    private javax.swing.JLabel lbLength;
    private javax.swing.JLabel lbLnameP;
    private javax.swing.JLabel lbNewAccounTurist;
    private javax.swing.JLabel lbNewTravel;
    private javax.swing.JLabel lbPartecipants;
    private javax.swing.JLabel lbPinasTravel;
    private javax.swing.JLabel lbPrezzoPrenotazione;
    private javax.swing.JLabel lbTravel;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbfname;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lbphone;
    private javax.swing.JList<String> lstAccounTurist;
    private javax.swing.JList<String> lstTravel;
    private javax.swing.JSpinner spDayPrice;
    private javax.swing.JTable tbPartecipants;
    private javax.swing.JTextField txCarriage;
    private javax.swing.JTextField txDepartureDate;
    private javax.swing.JTextField txDestination;
    private javax.swing.JTextField txDestinationP;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txFname;
    private javax.swing.JTextField txFnameP;
    private javax.swing.JTextField txLength;
    private javax.swing.JTextField txLname;
    private javax.swing.JTextField txLnameP;
    private javax.swing.JTextField txPhone;
    // End of variables declaration//GEN-END:variables

    private void refreshListaccounturist() {
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement("SELECT idAccounTurist, concat(Lname,' ',Fname) as turista FROM pinastravel.accounturist order by turista;");
            ResultSet rs = stmt.executeQuery();
            DefaultListModel model = new DefaultListModel();
            listIdaccounturist.clear();
            while (rs.next()) {
                model.addElement(rs.getString("turista"));
                listIdaccounturist.add(rs.getInt("idAccounTurist"));
            }
            lstAccounTurist.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void refreshListtravel() {
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement("SELECT idTravel,concat(Destination,' - ',Length,' giorni',' - ',DayPrice,' € al giorno') as destinazione FROM pinastravel.travel order by destinazione;");
            ResultSet rs = stmt.executeQuery();
            DefaultListModel model = new DefaultListModel();
            listIdtravel.clear();
            while (rs.next()) {
                model.addElement(rs.getString("destinazione"));
                listIdtravel.add(rs.getInt("idTravel"));

            }
            lstTravel.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void refreshtbPartecipants() {
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement("UPDATE partecipants p INNER JOIN travel t ON p.Destination = t.Destination SET p.TotalPrice = (t.DayPrice * t.Length)");
            stmt.executeUpdate();

            stmt = conn.prepareStatement("SELECT Fname, Lname, Destination, TotalPrice FROM pinastravel.partecipants ORDER BY Lname DESC");
            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tbPartecipants.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                String Nome = rs.getString("Fname");
                String Cognome = rs.getString("Lname");
                String Città = rs.getString("Destination");
                BigDecimal PrezzoFinale = rs.getBigDecimal("TotalPrice");

                Object[] record = new Object[]{Nome, Cognome, Città, PrezzoFinale};
                model.addRow(record);
            }

            tbPartecipants.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
